/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x03)
#define ID_SLIDER_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_2 (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x06)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 285, 240, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 80, 45, 130, 25, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 80, 5, 120, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 80, 85, 120, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 80, 165, 120, 20, 0, 0x64, 0 },

	

	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 80, 125, 130, 25, 0, 0x0, 0 },

	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 23, 195, 241, 34, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem, hItem1;
	int     NCode;
	int     Id;

	switch (pMsg->MsgId) {

		//控件初始化
	case WM_INIT_DIALOG:
		//第一项text控件初始化
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); //居中显示
		TEXT_SetText(hItem, "OUT_MUTE"); //显示字符串
		TEXT_SetFont(hItem, GUI_FONT_20_1);

		//第二项text控件初始化
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); //居中显示
		TEXT_SetText(hItem, "OUT_Invert"); //显示字符串
		TEXT_SetFont(hItem, GUI_FONT_20_1);

		//第三项text控件初始化
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER); //居中显示
		TEXT_SetText(hItem, "OUT_GAIN:"); //显示字符串
		TEXT_SetFont(hItem, GUI_FONT_20_1);

		//复选框控件初始化
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "OUT-Mute");
		CHECKBOX_SetFont(hItem, GUI_FONT_20_1);
		CHECKBOX_SetState(hItem, 0); //设置复选框当前状态

		//第二个复选框控件初始化
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "OUT-Invert");
		CHECKBOX_SetFont(hItem, GUI_FONT_20_1);
		CHECKBOX_SetState(hItem, 0); //设置复选框当前状态

		//初始化滑块
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
		SLIDER_SetRange(hItem, -80, 0); //设置滑块范围
		SLIDER_SetValue(hItem, -80); //设置滑块的值
		break;
		/*****************************绘制2D背景*******************************/
	case WM_PAINT:
		//全局背景
		GUI_SetBkColor(GUI_LIGHTBLUE);
		GUI_Clear();

		//第一项
		GUI_SetColor(GUI_RED);
		GUI_FillRect(0, 0, 285, 30);

		//第二项
		GUI_SetColor(GUI_RED);
		GUI_FillRect(0, 80, 285, 110);

		//第三项
		GUI_FillRect(0, 160, 285, 190);

		//画线
		GUI_SetColor(GUI_BLACK);
		GUI_DrawHLine(30, 0, 285);
		GUI_DrawHLine(80, 0, 285);
		GUI_DrawHLine(110, 0, 285);
		GUI_DrawHLine(160, 0, 285);
		GUI_DrawHLine(190, 0, 285);

		break;
		/**********************************************************************/
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Out_fristchild(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
