/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "BUTTON_Private.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_1 (GUI_ID_USER + 0x02)
#define ID_SLIDER_2 (GUI_ID_USER + 0x03)
#define ID_SLIDER_3 (GUI_ID_USER + 0x04)
#define ID_SLIDER_4 (GUI_ID_USER + 0x05)
#define ID_SLIDER_5 (GUI_ID_USER + 0x06)
#define ID_SLIDER_6 (GUI_ID_USER + 0x07)
#define ID_SLIDER_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_0 (GUI_ID_USER + 0x09)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x0A)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x0B)
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x0C)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x0D)
#define ID_CHECKBOX_4 (GUI_ID_USER + 0x0E)
#define ID_CHECKBOX_5 (GUI_ID_USER + 0x0F)
#define ID_CHECKBOX_6 (GUI_ID_USER + 0x10)
#define ID_CHECKBOX_7 (GUI_ID_USER + 0x11)
#define ID_TEXT_1 (GUI_ID_USER + 0x12)
#define ID_TEXT_2 (GUI_ID_USER + 0x13)
#define ID_TEXT_3 (GUI_ID_USER + 0x14)
#define ID_TEXT_4 (GUI_ID_USER + 0x15)
#define ID_TEXT_5 (GUI_ID_USER + 0x16)
#define ID_TEXT_6 (GUI_ID_USER + 0x17)
#define ID_TEXT_7 (GUI_ID_USER + 0x18)
#define ID_TEXT_8 (GUI_ID_USER + 0x19)
#define ID_BUTTON_0		(GUI_ID_USER + 0x1A)
#define ID_BUTTON_1		(GUI_ID_USER + 0x1B)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
#define Text_y  195
#define text_color GUI_BLACK
static char value[8]; //用来显示的值

static Input_Third_data * In_Third;
static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10, 0 },
	{ 20, 10 },
	{ 10, 20 },
};

//页面显示的字符串数据
static char face_string[][20] = 
{
	"NULL",
	"INPUT1 PAGE 3/3",
	"INPUT2 PAGE 3/3",
	"INPUT3 PAGE 3/3",
	"INPUT4 PAGE 3/3",
	"INPUT5 PAGE 3/3",
	"INPUT6 PAGE 3/3",
	"COAX PAGE 3/3",

};
//无效区域设置
static GUI_RECT Rect[] =
{
	{ 10,  Text_y, 40,  Text_y+20 },
	{ 50,  Text_y, 80,  Text_y+20 },
	{ 90, Text_y, 120, Text_y+20 },
	{ 130, Text_y, 160, Text_y+20 },
	{ 170, Text_y, 200, Text_y+20 },
	{ 210, Text_y, 240, Text_y+20 },
	{ 250, Text_y, 280, Text_y+20 },
	{ 290, Text_y, 320, Text_y+20 },
};

//显示滑块值
static void _ShowSlidervalue(void)
{
	GUI_SetColor(GUI_BLACK); //设置颜色
	GUI_SetTextMode(GUI_TM_TRANS); //设置透明模式
	GUI_SetFont(&GUI_Font20_1); //设置字体

//	GUI_GotoXY(10, Text_y);  //设置1位置
//	GUI_DispDecMin(-value[0]); //显示值
//	GUI_GotoXY(50, Text_y);  //设置2位置
//	GUI_DispDecMin(-value[1]); //显示值
//	GUI_GotoXY(90, Text_y);  //设置3位置
//	GUI_DispDecMin(-value[2]); //显示值
//	GUI_GotoXY(130, Text_y);  //设置4位置
//	GUI_DispDecMin(-value[3]); //显示值
//	GUI_GotoXY(170, Text_y);  //设置5位置
//	GUI_DispDecMin(-value[4]); //显示值
//	GUI_GotoXY(210, Text_y);  //设置6位置
//	GUI_DispDecMin(-value[5]); //显示值
//	GUI_GotoXY(250, Text_y);  //设置7位置
//	GUI_DispDecMin(-value[6]); //显示值
//	GUI_GotoXY(290, Text_y);  //设置8位置
//	GUI_DispDecMin(-value[7]); //显示值
	
	GUI_GotoXY(10, Text_y);  //设置1位置
	GUI_DispDecMin(-In_Third->data.Aux1_SLIDER_DATA); //显示值
	GUI_GotoXY(50, Text_y);  //设置2位置
	GUI_DispDecMin(-In_Third->data.Aux2_SLIDER_DATA); //显示值
	GUI_GotoXY(90, Text_y);  //设置3位置
	GUI_DispDecMin(-In_Third->data.Aux3_SLIDER_DATA); //显示值
	GUI_GotoXY(130, Text_y);  //设置4位置
	GUI_DispDecMin(-In_Third->data.Aux4_SLIDER_DATA); //显示值
	GUI_GotoXY(170, Text_y);  //设置5位置
	GUI_DispDecMin(-In_Third->data.Aux5_SLIDER_DATA); //显示值
	GUI_GotoXY(210, Text_y);  //设置6位置
	GUI_DispDecMin(-In_Third->data.Aux6_SLIDER_DATA); //显示值
	GUI_GotoXY(250, Text_y);  //设置7位置
	GUI_DispDecMin(-In_Third->data.Aux7_SLIDER_DATA); //显示值
	GUI_GotoXY(290, Text_y);  //设置8位置
	GUI_DispDecMin(-In_Third->data.Aux8_SLIDER_DATA); //显示值
	
	AT24C16_PageWrite((u8 *)In_Third,IIC_Addr[(In_Third->face_switch)+7],sizeof(Input_Data3));  //保存数据
}
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 5, 40, 34, 150, SLIDER_CF_VERTICAL, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 45, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_2, 85, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_3, 125, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_4, 165, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_5, 205, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_6, 245, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_7, 285, 40, 34, 150, 8, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 330, 35, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 330, 60, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_2, 330, 85, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_3, 330, 110, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_4, 330, 135, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_5, 330, 160, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_6, 330, 185, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_7, 330, 210, 60, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 8, 212, 30, 240-212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 48, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 88, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4, 128, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5, 168, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_6, 208, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_7, 248, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_8, 288, 212, 30, 240 - 212, 0, 0, 0 },
	
	/*页面切换*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 5, 5, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 375, 5, 20, 25, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
// USER END
//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

//右边三角形
#define BUTTON_H2P(h) (BUTTON_Obj*) GUI_ALLOC_h2p(h)

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	BUTTON_Obj * pObj; //用来提取出按钮的指针结构体，包含了各种信息

	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;
	pObj = BUTTON_H2P(hWin);

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}

		//绘制聚焦,如果不接受聚焦则此项不起作用
		if (pObj->Widget.State & WIDGET_STATE_FOCUS)
		{
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;


		//case WM_TOUCH:
		//	if (pMsg->Data.p) {  /* Something happened in our area (pressed or released) */
		//		if (pState->Pressed) {
		//			RMSTC_Value++;
		//			WIDGET_OrState(hWin, BUTTON_STATE_PRESSED);
		//			WM_NotifyParent(hWin, WM_NOTIFICATION_CLICKED);
		//		}
		//		else {
		//			/* React only if button was pressed before ... avoid problems with moving / hiding windows above (such as dropdown) */
		//			
		//		}
		//	}
		//	else {
		//		
		//	}
		//	break;
		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem;
	int     NCode;
	int     Id;

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, In_Third->String);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_WHITE);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "AUX1");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "AUX2");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "AUX3");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);


		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetText(hItem, "AUX4");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetText(hItem, "AUX5");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetText(hItem, "AUX6");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetText(hItem, "AUX7");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetText(hItem, "AUX8");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		//复选框
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "AUX1");
		CHECKBOX_SetTextColor(hItem,GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux1_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "AUX2");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux2_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetText(hItem, "AUX3");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux3_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetText(hItem, "AUX4");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux4_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
		CHECKBOX_SetText(hItem, "AUX5");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux5_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
		CHECKBOX_SetText(hItem, "AUX6");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux6_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
		CHECKBOX_SetText(hItem, "AUX7");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux7_CHECKBOX_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
		CHECKBOX_SetText(hItem, "AUX8");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
		CHECKBOX_SetState(hItem,In_Third->data.Aux8_CHECKBOX_STA);

		//滑块
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux1_SLIDER_DATA);
		//SLIDER_SetSkin(hItem, SLIDER_DrawSkinFlex); //可以用回之前的皮肤


		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux2_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux3_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux4_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux5_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux6_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux7_SLIDER_DATA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, In_Third->data.Aux8_SLIDER_DATA);

		/*重新设计按钮的外观*/
		
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		
		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点


		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_SLIDER_0: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
				In_Third->data.Aux1_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[0]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_1: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1); //获得滑块句柄
				In_Third->data.Aux2_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[1]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_2: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2); //获得滑块句柄
				In_Third->data.Aux3_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[2]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_3: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3); //获得滑块句柄
				In_Third->data.Aux4_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[3]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_4: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4); //获得滑块句柄
				In_Third->data.Aux5_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[4]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_5: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5); //获得滑块句柄
				In_Third->data.Aux6_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[5]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_6: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6); //获得滑块句柄
				In_Third->data.Aux7_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值

				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7), value[6]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_7: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7); //获得滑块句柄
				In_Third->data.Aux8_SLIDER_DATA = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值

				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6), value[7]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		
		//复选框
		case ID_CHECKBOX_0:
			//发生什么变化
			switch (NCode)
			{
			//复选框已被点击
			case WM_NOTIFICATION_CLICKED:
				break;

			//复选框已被释放
			case WM_NOTIFICATION_RELEASED:
				break;

			//复选框的状态已改变
			case WM_NOTIFICATION_VALUE_CHANGED:
				//因为用了CHECKBOX_SetState，所以无点击时也会进入该选项-次
				//为了让创建复选框时不进行状态标记的转换
				if(In_Third->checkbox_sta & (0x01<<0))
				{
					if(In_Third->data.Aux1_CHECKBOX_STA == 0)
					{
						In_Third->data.Aux1_CHECKBOX_STA = 1;
					}
					else
					{
						In_Third->data.Aux1_CHECKBOX_STA = 0;
					}
				}
				else
				{
					In_Third->checkbox_sta |= (0x01<<0);
				}

				break;
			}
			break; 
			
		case ID_CHECKBOX_1:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<1))
					{
						if(In_Third->data.Aux2_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux2_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux2_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<1);
					}

					break;
			}
			break; 
			
			case ID_CHECKBOX_2:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<2))
					{
						if(In_Third->data.Aux3_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux3_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux3_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<2);
					}

					break;
			}
			break;
			
		case ID_CHECKBOX_3:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<3))
					{
						if(In_Third->data.Aux4_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux4_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux4_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<3);
					}

					break;
			}
			break;
			
		case ID_CHECKBOX_4:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<4))
					{
						if(In_Third->data.Aux5_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux5_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux5_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<4);
					}

					break;
			}
			break;
			
		case ID_CHECKBOX_5:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<5))
					{
						if(In_Third->data.Aux6_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux6_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux6_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<5);
					}

					break;
			}
			break;
			
		case ID_CHECKBOX_6:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<6))
					{
						if(In_Third->data.Aux7_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux7_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux7_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<6);
					}

					break;
			}
			break;
			
		case ID_CHECKBOX_7:
			//发生什么变化
			switch (NCode)
			{
				//复选框已被点击
				case WM_NOTIFICATION_CLICKED:
					break;

				//复选框已被释放
				case WM_NOTIFICATION_RELEASED:
					break;

				//复选框的状态已改变
				case WM_NOTIFICATION_VALUE_CHANGED:
					//为了让创建复选框时不进行状态标记的转换
					if(In_Third->checkbox_sta & (0x01<<7))
					{
						if(In_Third->data.Aux8_CHECKBOX_STA == 0)
						{
							In_Third->data.Aux8_CHECKBOX_STA = 1;
						}
						else
						{
							In_Third->data.Aux8_CHECKBOX_STA = 0;
						}
					}
					else
					{
						In_Third->checkbox_sta |= (0x01<<7);
					}

					break;
			}
			break;
			
		
		//页面切换
		case ID_BUTTON_0:
			switch (NCode)
			{
			//已点击按钮
			case WM_NOTIFICATION_CLICKED:

				break;

			//已释放按钮
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
				hWin_now = Input_Four();      //切换下一个界面
				break;
			}
			break;

		case ID_BUTTON_1:
			switch (NCode)
			{
			//已点击按钮
			case WM_NOTIFICATION_CLICKED:

				break;

			//已释放按钮
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
				hWin_now = Input_Second();      //切换下一个界面
				break;
			}
			break;
			
			
		}
		break; //end of case WM_NOTIFY_PARENT
		
	

	case WM_PAINT:

		//背景
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//第一项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		//滑块背景
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRoundedRect(0, 35, 320, 236, 4);

		//色块
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(325, 34, 395, 236, 4);
		/*GUI_SetColor(GUI_BLACK);
		GUI_FillRoundedRect(0, 200, 320, 240, 4);*/

		//显示值色块
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(5, Text_y, 41, Text_y + 17, 2);
		GUI_FillRoundedRect(45, Text_y, 81, Text_y + 17, 2);
		GUI_FillRoundedRect(85, Text_y,  121, Text_y + 17, 2);
		GUI_FillRoundedRect(125, Text_y, 161, Text_y + 17, 2);
		GUI_FillRoundedRect(165, Text_y, 201, Text_y + 17, 2);
		GUI_FillRoundedRect(205, Text_y, 241, Text_y + 17, 2);
		GUI_FillRoundedRect(245, Text_y, 281, Text_y + 17, 2);
		GUI_FillRoundedRect(285, Text_y, 318, Text_y + 17, 2);

		_ShowSlidervalue(); //显示数值
		break;


	
	/*********************************自定义信息**********************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
		GUI_SendKeyMsg(GUI_KEY_LEFT,1); //滑块数值减少
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
		GUI_SendKeyMsg(GUI_KEY_RIGHT,1); //滑块数值增加
		break;
	
	//CONTROL按下
	case MSG_KEY_CONTROL:
		GUI_SendKeyMsg(GUI_KEY_SPACE,1);
		break;
	
	//页面切换
	case MSG_KNOB_OUT_LEFT:	
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Second();      //切换下一个界面
		break;
	
	case MSG_KNOB_OUT_RIGHT:
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Four();      //切换下一个界面
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1);  //退出
		break;
	/****************************************END********************************************/
	/*********************************按键处理******************************************/
	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
		{
			//ESC
			case GUI_KEY_ESCAPE:
            GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
            hWin_now = Input_First();  //显示Input_First页面
			INPUT_CHANNEL = 1;
            break;
		}
		break;
		
	//可以在这里释放数据结构
	case WM_DELETE:
		myfree(0,In_Third); //释放动态内存
		break;
	
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//初始化数据
static void Init_data(Input_Third_data *L)
{
//	L->data.Aux1_SLIDER_DATA 	= 80;
//	L->data.Aux2_SLIDER_DATA 	= 80;
//	L->data.Aux3_SLIDER_DATA 	= 80;
//	L->data.Aux4_SLIDER_DATA 	= 80;
//	L->data.Aux5_SLIDER_DATA 	= 80;
//	L->data.Aux6_SLIDER_DATA 	= 80;
//	L->data.Aux7_SLIDER_DATA 	= 80;
//	L->data.Aux8_SLIDER_DATA 	= 80;
//	L->data.Aux1_CHECKBOX_STA	= 0;
//	L->data.Aux2_CHECKBOX_STA	= 0;
//	L->data.Aux3_CHECKBOX_STA	= 0;
//	L->data.Aux4_CHECKBOX_STA	= 0;
//	L->data.Aux5_CHECKBOX_STA	= 0;
//	L->data.Aux6_CHECKBOX_STA	= 0;
//	L->data.Aux7_CHECKBOX_STA	= 0;
//	L->data.Aux8_CHECKBOX_STA	= 0;
	
	L->face_switch  	= 	INPUT_CHANNEL;  //获得选中的通道
	L->String       	= 	face_string[INPUT_CHANNEL]; //头项目字符串
	L->Time_count       =	0;
	L->hItime			=	0;
	L->Key_count		=	0;
	L->Released			=	0;
	L->checkbox_sta     =   0;
	AT24C16_PageRead((u8 *)L,IIC_Addr[(L->face_switch)+7],sizeof(Input_Data3));  //提取数据
}


WM_HWIN Input_Third(void) {
	WM_HWIN hWin;
	
	//申请数据
	In_Third = (Input_Third_data *)mymalloc(0,sizeof(Input_Third_data));
	
	if(In_Third == NULL)
	{
		return 0;
	}
	else
	{
		Init_data(In_Third);
	}
	
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
