/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "BUTTON_Private.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_TEXT_1 (GUI_ID_USER + 0x05)
#define ID_TEXT_2 (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_9 (GUI_ID_USER + 0x10)
#define ID_BUTTON_10 (GUI_ID_USER + 0x11)
#define ID_BUTTON_11 (GUI_ID_USER + 0x12)
#define ID_BUTTON_12 (GUI_ID_USER + 0x13)
#define ID_BUTTON_13 (GUI_ID_USER + 0x14)
#define ID_BUTTON_14 (GUI_ID_USER + 0x15)

//COMPRESS
#define ID_BUTTON_15 (GUI_ID_USER + 0x16)
#define ID_BUTTON_16 (GUI_ID_USER + 0x17)
#define ID_BUTTON_17 (GUI_ID_USER + 0x18)
#define ID_BUTTON_18 (GUI_ID_USER + 0x19)
#define ID_BUTTON_19 (GUI_ID_USER + 0x1A)
#define ID_BUTTON_20 (GUI_ID_USER + 0x1B)
#define ID_BUTTON_21 (GUI_ID_USER + 0x1C)
#define ID_BUTTON_22 (GUI_ID_USER + 0x1D)
#define ID_BUTTON_23 (GUI_ID_USER + 0x1E)
#define ID_BUTTON_24 (GUI_ID_USER + 0x1F)

#define ID_BUTTON_25 (GUI_ID_USER + 0x20)
#define ID_BUTTON_26 (GUI_ID_USER + 0x21)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10, 0 },
	{ 20, 10 },
	{ 10, 20 },
};

static u8 check_sate[2] = {0}; //用来针对复选框的变量
/***************************************该页面需要用到的数据***************************************/
//申请关于Input界面的数据
static Input_Second_data *Data_p; //数据结构体指针
	
//页面显示的字符串数据
static char face_string[][20] = 
{
	"NULL",
	"INPUT1 PAGE 1/3",
	"INPUT2 PAGE 1/3",
	"INPUT3 PAGE 1/3",
	"INPUT4 PAGE 1/3",
	"INPUT5 PAGE 1/3",
	"INPUT6 PAGE 1/3",
	"COAX PAGE 1/3",

};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 36, 194, 28, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 172, 194, 28, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 202, 36, 194, 28, 0, 0, 0 },
	//创建按钮
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 68, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 102, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 136, 98, 32, 0, 0x0, 0 },
	
	//创建复选框
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 5, 208, 90, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 107, 208, 90, 23, 0, 0x0, 0 },

	/*第三项*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 355, 36, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 202, 68, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 202, 102, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 202, 136, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 202, 170, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 202, 204, 98, 32, 0, 0x0, 0 },

	/*增减按钮*/
	//NOISEGATE
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 104, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 104, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 104, 141, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 175, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 175, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_14, 175, 141, 20, 25, 0, 0x0, 0 },

	//COMPRESSOR
	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_15, 104 + 202, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_16, 104 + 202, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_17, 104 + 202, 141, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_18, 104 + 202, 174, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_19, 104 + 202, 208, 20, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_20, 175 + 200, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_21, 175 + 200, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_22, 175 + 200, 141, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_23, 175 + 200, 174, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_24, 175 + 200, 208, 20, 25, 0, 0x0, 0 },

	/*页面切换*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_25, 5, 5, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_26, 375, 5, 20, 25, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

//右边三角形
#define BUTTON_H2P(h) (BUTTON_Obj*) GUI_ALLOC_h2p(h)

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	BUTTON_Obj * pObj; //用来提取出按钮的指针结构体，包含了各种信息

	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;
	pObj = BUTTON_H2P(hWin);

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}

		//绘制聚焦,如果不接受聚焦则此项不起作用
		if (pObj->Widget.State & WIDGET_STATE_FOCUS)
		{
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;


		//case WM_TOUCH:
		//	if (pMsg->Data.p) {  /* Something happened in our area (pressed or released) */
		//		if (pState->Pressed) {
		//			RMSTC_Value++;
		//			WIDGET_OrState(hWin, BUTTON_STATE_PRESSED);
		//			WM_NotifyParent(hWin, WM_NOTIFICATION_CLICKED);
		//		}
		//		else {
		//			/* React only if button was pressed before ... avoid problems with moving / hiding windows above (such as dropdown) */
		//			
		//		}
		//	}
		//	else {
		//		
		//	}
		//	break;
		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}


//子项x，y坐标定义
#define RMSTC_X  		125
#define RMSTC_Y  		75
#define HOLD_X  		RMSTC_X
#define HOLD_Y  		RMSTC_Y+34
#define DECAY_X 		RMSTC_X
#define DECAY_Y 		RMSTC_Y+68
#define THRSH_X 		RMSTC_X + 204
#define THRSH_Y			RMSTC_Y
#define RATIO_X			RMSTC_X + 204
#define RATIO_Y			HOLD_Y
#define ATK_TIME_X		RMSTC_X + 204
#define ATK_TIME_Y  	DECAY_Y
#define RELEASE_X		RMSTC_X + 204
#define RELEASE_Y		ATK_TIME_Y + 34
#define COM_HOLD_X		RMSTC_X + 204
#define COM_HOLD_Y		RELEASE_Y + 34

//定义最大最小值
#define RMSTC_DATA_MAX   10000
#define RMSTC_DATA_MIN   1
#define HOLD_DATA_MAX    2000
#define HOLD_DATA_MIN    0
#define DECAY_DATA_MAX   



//定义无效区域
static const GUI_RECT InvaliRect_Value[][4] = {
	{ 125, 70, 	205, 	90 }, //RMSTC_Item
	{ 125, 104,	205,	124}, //HOLD_Item
};

/*
*******************************************************************************************
* 函 数 名: Max_Min
* 功能说明: 限制最大和最小值
* 形 参: 最大值和最小值
* 返 回 值: 无
*******************************************************************************************
*/
void Max_Min(void *p,u16 Max,u16 Min)
{
	s16 *q = (s16 *)p;
	if((*q)>Max)
	{
		*q = Max;
	}
	else if((*q)<Min)
	{
		*q = Min;
	}
}

/*
*******************************************************************************************
* 函 数 名: Show_Value
* 功能说明: 显示数值
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/



static void Show_Value(void)
{
	u16 max,min; //最大和最小值
	GUI_SetColor(GUI_BLACK); 		//设置颜色
	GUI_SetTextMode(GUI_TM_TRANS);  //设置透明模式
	GUI_SetFont(&GUI_Font20_1); 	//设置字体
	
	//RMSTC
	GUI_GotoXY(RMSTC_X, RMSTC_Y);  				//设置RMSTC位置
	Max_Min(&Data_p->data.RMSTC_DATA,RMSTC_DATA_MAX,RMSTC_DATA_MIN);  //限制值
	GUI_DispDecMin(Data_p->data.RMSTC_DATA); 		//显示设置RMSTC位值
	
	//HOLD

	GUI_GotoXY(HOLD_X, HOLD_Y);  				//设置HOLD位置
	Max_Min(&Data_p->data.HOLD_DATA,HOLD_DATA_MAX,HOLD_DATA_MIN);    //限制值
	GUI_DispDecMin(Data_p->data.HOLD_DATA); 			//显示设置HOLD位值
	
	
	//DECAY
	GUI_GotoXY(DECAY_X, DECAY_Y);  				//设置DECAY位置
	GUI_DispDecMin(Data_p->data.DECAY_DATA); 		//显示设置DECAY位值
	
	//THRSH
	GUI_GotoXY(THRSH_X, THRSH_Y);  				//设置THRSH位置
	GUI_DispDecMin(Data_p->data.THRSH_DATA); 		//显示设置THRSH位值
	
	
	//RATIO
	GUI_GotoXY(RATIO_X, RATIO_Y);  				//设置RATIO位置
	GUI_DispDecMin(Data_p->data.RATIO_DATA); 		//显示设置RATIO位值
	
	//ATK_TIME
	GUI_GotoXY(ATK_TIME_X, ATK_TIME_Y);  		//设置ATK_TIME位置
	GUI_DispDecMin(Data_p->data.ATK_TIME_DATA); 		//显示设置ATK_TIME位值
	
	//RELEASE
	GUI_GotoXY(RELEASE_X, RELEASE_Y);  			//设置RELEASE位置
	GUI_DispDecMin(Data_p->data.RELEASE_DATA); 		//显示设置RELEASE位值
	
	//COM_HOLD
	GUI_GotoXY(COM_HOLD_X, COM_HOLD_Y);  		//设置COM_HOLD位置
	GUI_DispDecMin(Data_p->data.COM_HOLD_DATA); 		//显示设置COM_HOLD位值
	
	AT24C16_PageWrite((u8 *)Data_p,IIC_Addr[Data_p->face_switch],sizeof(Input_Data));  //保存数据
	
}
/*
*******************************************************************************************
* 函 数 名: Value_Change_add
* 功能说明: 增加数值
* 形 参: 数值的地址
* 返 回 值: 无
*******************************************************************************************
*/
void Value_Change_add(void *p,u16 *time)
{
	
	s16 *q = (s16 *)p;
	(*time)++;
	if ((*time) < 10)
	{
		(*q)++;
	}
	else if ((*time) < 30)
	{
		(*q) += 10;
	}
	else if ((*time) >= 30)
	{
		(*q) += 100;
	}

}
/*
*******************************************************************************************
* 函 数 名: Value_Change_dec
* 功能说明: 减少数值
* 形 参: 数值的地址
* 返 回 值: 无
*******************************************************************************************
*/
void Value_Change_dec(void *p,u16 *time)
{
	
	s16 *q = (s16 *)p;
	(*time)++;
	if ((*time) < 10)
	{
		(*q)--;
	}
	else if ((*time) < 30)
	{
		(*q) -= 10;
	}
	else if ((*time) >= 30)
	{
		(*q) -= 100;
	}

}
/*****************************************************Static code End**********************************************/
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem;
	int		NCode;
	int		Id;

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END

	case WM_INIT_DIALOG:
		//TEXT设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, Data_p->String); //显示字符串数据
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//NOISEGATE
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "NOISEGATE");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//MUTE_AND_INVERT
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "MUTE_AND_INVERT");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_20B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//COMPRESSOR
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "COMPRESSOR");
		//TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//按钮设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "RMSTC(dB/s)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "HOLD(ms)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "DECAY(dB/s)");          //设置显示的字符串
		
		//ON_OFF
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		if((Data_p->data.ON_OFF&0x01) == 0)
		{
			BUTTON_SetText(hItem, "ON");          //设置显示的字符串
		}
		else
		{
			BUTTON_SetText(hItem, "OFF");          //设置显示的字符串
		}
		
		//COMPRESS
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "THRSH(dB)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "RATIO");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "ATK TIME(ms)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		BUTTON_SetFont(hItem, GUI_FONT_13HB_1);  //设置字体
		BUTTON_SetText(hItem, "RELEASE TIME");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "HOLD(ms)");          //设置显示的字符串

		//复选框
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "IN_MUTE");        //设置显示字符串
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);   //设置字体颜色
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);  //设置聚焦颜色
		CHECKBOX_SetFont(hItem, GUI_FONT_13H_1);   //设置字体大小
		CHECKBOX_SetState(hItem,Data_p->data.IN_MUTE_STA); //设置初始显示状态

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "IN_INVERT");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);  
		CHECKBOX_SetFont(hItem, GUI_FONT_13H_1);
		CHECKBOX_SetState(hItem,Data_p->data.IN_INVERT_STA);

		/*重新设计按钮的外观*/
		//NOISEGATE
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//COMPRESSOR
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_SetCallback(hItem, _cbButton_left);

		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_20);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_21);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_22);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_23);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_24);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//切换按钮
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		break;
		
	//可以在这里释放数据结构
	case WM_DELETE:
		//后续需要添加保存数据到IC240C中的代码
		myfree(0,Data_p); //释放动态内存
		check_sate[0] = 0; //用来标记复选框的
		check_sate[1] = 0;
		break;
	
	case WM_PAINT:
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//第一项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		//第二项 NOISEGATE
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(0, 34, 198, 64, 4);

		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(102, 68, 198, 98, 4);
		GUI_FillRoundedRect(102, 102, 198, 132, 4);
		GUI_FillRoundedRect(102, 136, 198, 166, 4);

		//第三项
		//右边第二项
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(202, 34, 398, 64, 4);


		//白色条
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(304, 68,  396, 98, 4);
		GUI_FillRoundedRect(304, 102, 396, 132, 4);
		GUI_FillRoundedRect(304, 136, 396, 166, 4);
		GUI_FillRoundedRect(304, 170, 396, 200, 4);
		GUI_FillRoundedRect(304, 204, 396, 234, 4);


		//第四项
		GUI_SetColor(GUI_BLUE);
		//MUTE_AND_INVERT
		GUI_FillRoundedRect(0, 170, 198, 200, 4);
		//MUTE
		GUI_FillRoundedRect(0, 204, 98, 234, 4);
		//INVERT
		GUI_FillRoundedRect(102, 204, 198, 234, 4);
		
		
		//显示各个子选项数值
		Show_Value();
		break;
		
	/**************************************子窗口发生变化通知消息***********************************************/	
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);  //获得是哪个子窗口发生变化
		NCode = pMsg->Data.v;          //子窗口发生什么变化
	
		//消息处理
		switch(Id)
		{
			//IN_MUTE子窗口发生变化
			case ID_CHECKBOX_0:
				//发生什么变化
				switch(NCode)
				{
					//复选框已被点击
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0)); //改变聚焦
						Data_p->Item = IN_MUTE_Item;  //子选项改变
                        break;
					
					//复选框已被释放
                    case WM_NOTIFICATION_RELEASED:
						
						break;
					
					//复选框的状态已改变
					case WM_NOTIFICATION_VALUE_CHANGED:
						if(check_sate[0])
						{
							if(Data_p->data.IN_MUTE_STA == 0)
							{
								Data_p->data.IN_MUTE_STA = 1;
							}
							else
							{
								Data_p->data.IN_MUTE_STA = 0;
							}
//							WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));//无效化该窗口
						}
						else
						{
							check_sate[0] = 1;
						}
						break;
				}
				break;
				
			//IN_INVERT子窗口发生变化
			case ID_CHECKBOX_1:
				//发生什么变化
				switch(NCode)
				{
					//复选框已被点击
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1)); //改变聚焦
						Data_p->Item = IN_INVERT_Item;  //子选项改变
                        break;
					
					//复选框已被释放
                    case WM_NOTIFICATION_RELEASED:
						
						break;
					
					//复选框的状态已改变
					case WM_NOTIFICATION_VALUE_CHANGED:
						if(check_sate[1])
						{
							if(Data_p->data.IN_INVERT_STA == 0)
							{
								Data_p->data.IN_INVERT_STA = 1;
							}
							else
							{
								Data_p->data.IN_INVERT_STA = 0;
							}
//							WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));//无效化该窗口
						}
						else
						{
							check_sate[1] = 1;
						}
						
					
						break;
				}
				break;
				
			//页面切换
			case ID_BUTTON_25:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						
						break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Input_Third();      //切换下一个界面
						break;
				}
				break;
				
			case ID_BUTTON_26:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						
						break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Input_Four();      //切换下一个界面
						break;
				}
				break;
				
			//子选项改变
			//RMSTC
			case ID_BUTTON_0:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0)); //改变聚焦
						Data_p->Item = RMSTC_Item;  //子选项改变
						break;

				}
				break;
				
			//HOLD
			case ID_BUTTON_1:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
						Data_p->Item = HOLD_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;

				}
				break;
			
			//DECAY
			case ID_BUTTON_2:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
						Data_p->Item = DECAY_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
				}
				break;
				
			//ON_OFF
			case ID_BUTTON_3:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
						Data_p->Item = ON_OFF_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Data_p->data.ON_OFF = ~Data_p->data.ON_OFF;  //切换显示的字符串
						if((Data_p->data.ON_OFF&0x01) == 0)
						{
							BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3), "ON");          //设置显示的字符串
						}
						else
						{
							BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3), "OFF");
						}
						WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));//无效化该窗口
						break;
				}
				break;
				
			//THRSH
			case ID_BUTTON_4:
				switch(NCode)
				{//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4));
						Data_p->Item =THRSH_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
				}
				break;
			
			//RATIO
			case ID_BUTTON_5:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5));
						Data_p->Item = RATIO_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
				}
				break;
				
			//ATK_TIME
			case ID_BUTTON_6:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6));
						Data_p->Item = ATK_TIME_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
				}
				break;
				
			//RELEASE
			case ID_BUTTON_7:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7));
						Data_p->Item = RELEASE_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
				}
				break;
				
			//COM_HOLD
			case ID_BUTTON_8:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));
						Data_p->Item = COM_HOLD_Item;
//						WM_MakeModal(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8));  //模态化窗口
						break;
					//已释放按钮
//					case WM_NOTIFICATION_RELEASED:
//						Data_p->Released = 0;
//						WM_MakeModal(0);
//						break;
					
//					//按钮已被点击，且指针已移出按钮并且没有释放
//					case WM_NOTIFICATION_MOVED_OUT:
//						Data_p->Released |= (1<<COM_HOLD_Item);  //没有释放按钮
//						break;
				}
				break;
				
			/*******************增减按钮*******************/
			//RMSTC
			case ID_BUTTON_9:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Data_p->data.RMSTC_DATA--;
						WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
						Data_p->hItime = WM_CreateTimer(pMsg->hWin, RMSTC_Time_left, 100, 0); //创建主窗口一个定时器
						// USER END
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Data_p->Time_count = 0;
						WM_DeleteTimer(Data_p->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_12:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Data_p->data.RMSTC_DATA++;
						WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
						Data_p->hItime = WM_CreateTimer(pMsg->hWin, RMSTC_Time_right, 100, 0); //创建主窗口一个定时器
						// USER END
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Data_p->Time_count = 0;
						WM_DeleteTimer(Data_p->hItime);
					break;
				}
				break;
				
			//HOLD
			case ID_BUTTON_10:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Data_p->data.HOLD_DATA--;
						WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
						Data_p->hItime = WM_CreateTimer(pMsg->hWin, HOLD_Time_left, 100, 0); //创建主窗口一个定时器
						// USER END
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Data_p->Time_count = 0;
						WM_DeleteTimer(Data_p->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_13:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Data_p->data.HOLD_DATA++;
						WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
						Data_p->hItime = WM_CreateTimer(pMsg->hWin, HOLD_Time_right, 100, 0); //创建主窗口一个定时器
						// USER END
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Data_p->Time_count = 0;
						WM_DeleteTimer(Data_p->hItime);
					break;
				}
				break; 
		}//end of switch(Id)
		break;
	/********************************定时器信息处理*************************************/
	case WM_TIMER:
		switch(WM_GetTimerId(pMsg->Data.v))  //根据不同定时器的ID号来处理不同的信息
		{
			//RMSTC_TIME
			case RMSTC_Time_left:
				if (BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9))) //判断按钮是否还在按下
				{
//					Data_p->Time_count++;
//					
//					if(Data_p->Time_count < 5)
//					{
//						Data_p->data.RMSTC_DATA --;
//					}
//					else if(Data_p->Time_count < 10)  //略长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA - 10;
//					}
//					else if(Data_p->Time_count < 15) //长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA - 100;
//					}
//					else if(Data_p->Time_count >= 15) //超长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA - 1000;
//					}
					Value_Change_dec(&Data_p->data.RMSTC_DATA,&Data_p->Time_count);
					WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
					WM_RestartTimer(pMsg->Data.v, 100); // 重启定时器
			
				}
				break;
			
			case RMSTC_Time_right:
				if (BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12))) //判断按钮是否还在按下
				{
//					Data_p->Time_count++;
//					if(Data_p->Time_count < 5)
//					{
//						Data_p->data.RMSTC_DATA ++;
//					}
//					else if(Data_p->Time_count < 10)  //略长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA + 10;
//					}
//					else if(Data_p->Time_count < 15) //长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA + 100;
//					}
//					else if(Data_p->Time_count >= 15) //超长按
//					{
//						Data_p->data.RMSTC_DATA = Data_p->data.RMSTC_DATA + 1000;
//					}
					
					Value_Change_add(&Data_p->data.RMSTC_DATA,&Data_p->Time_count);
					
					WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
					WM_RestartTimer(pMsg->Data.v, 100); // 重启定时器
			
				}
				break;
			
			//HOLD_TIME
			case HOLD_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10)))
				{

					Value_Change_dec(&Data_p->data.HOLD_DATA,&Data_p->Time_count);
					WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
					WM_RestartTimer(pMsg->Data.v, 100); // 重启定时器
				}
				break;
				
			case HOLD_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13)))
				{

					Value_Change_add(&Data_p->data.HOLD_DATA,&Data_p->Time_count);
					WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
					WM_RestartTimer(pMsg->Data.v, 100); // 重启定时器
				}
				break;
		}
		break;
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		
		//子选项指示
		if(Data_p->Item == COM_HOLD_Item)
		{
			Data_p->Item = RMSTC_Item;
		}
		else
		{
			Data_p->Item++;
		}
		
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		//子选项指示
		if(Data_p->Item == RMSTC_Item)
		{
			Data_p->Item = COM_HOLD_Item;
		}
		else
		{
			Data_p->Item--;
		}
		
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//CONTROL按下
	case MSG_KEY_CONTROL:
		if((Data_p->Item == IN_MUTE_Item)||(Data_p->Item == IN_INVERT_Item)) //IN_MUTE_Item和IN_INVERT_Item项
		{
			GUI_SendKeyMsg(GUI_KEY_SPACE,1);
		}
		else
		{
			GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		}
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1);  //退出
		break;
	
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
		//根据选中的子选项来做不同的操作
		switch(Data_p->Item)
		{
			//RMSTC子项目
			case RMSTC_Item:

				//RMSTC_DATA增加
				Value_Change_add(&Data_p->data.RMSTC_DATA,&Data_p->Key_count);  
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
				break;
			
			//HOLD子项目
			case HOLD_Item:
				//HOLD_DATA增加
				Value_Change_add(&Data_p->data.HOLD_DATA,&Data_p->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
				break;
		}
		
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
//		Data_p->Key_count++;
		//根据选中的子选项来做不同的操作
		switch(Data_p->Item)
		{
			case RMSTC_Item:

				//RMSTC减少
				Value_Change_dec(&Data_p->data.RMSTC_DATA,&Data_p->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
				break;
				
			case HOLD_Item:
				Value_Change_dec(&Data_p->data.HOLD_DATA,&Data_p->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[HOLD_Item]); //无效化该区域重新刷新
				break;
		}
		break;
	
	//页面切换
	case MSG_KNOB_OUT_LEFT:	
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Four();      //切换下一个界面
		break;
	
	case MSG_KNOB_OUT_RIGHT:
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Third();      //切换下一个界面
		break;
	//没有旋钮动作
	case MSG_KNOB_NULL:
		Data_p->Key_count = 0;
		break;
	/*********************************按键处理******************************************/
	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
		{
			//ESC
			case GUI_KEY_ESCAPE:
            GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
            hWin_now = Input_First();  //显示Input_First页面
			INPUT_CHANNEL = 1;
            break;
		}
		break;
	
	/*********************************默认信息处理***************************************/
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

//初始化数据
static void Init_data(Input_Second_data *L)
{
	//后续需要在IC240C中提取数据
	L->face_switch  	= 	INPUT_CHANNEL;  //获得选中的通道
	L->Item         	= 	RMSTC_Item;              //子选项
	L->String       	= 	face_string[INPUT_CHANNEL]; //头项目字符串
	L->Time_count       =	0;
	L->hItime			=	0;
	L->Key_count		=	0;
	L->Released			=	0;
	
	//初始化才用到
//	L->data.RMSTC_DATA   	=   1;
//	L->data.HOLD_DATA    	= 	0;
//	L->data.DECAY_DATA		= 	1;
//	L->data.IN_MUTE_STA		=	0;
//	L->data.IN_INVERT_STA	=	0;
//	L->data.ON_OFF			=	0;
//	L->data.THRSH_DATA		=	0;
//	L->data.RATIO_DATA		=	0;
//	L->data.ATK_TIME_DATA	=	0;
//	L->data.RELEASE_DATA		=	0;
//	L->data.COM_HOLD_DATA	=	0;

	AT24C16_PageRead((u8 *)(&(L->data)),IIC_Addr[L->face_switch],sizeof(Input_Data));  //提取数据
}

WM_HWIN Input_Second(void) {
	WM_HWIN hWin;
	
	//申请数据
	Data_p = (Input_Second_data *)mymalloc(0,sizeof(Input_Second_data)); //申请动态内存
	if(Data_p == NULL) //如果申请不成功，会错误
		return 0;
	else 
		Init_data(Data_p);   //申请成功就初始化数据
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
