/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x0B)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
struct SweepFreq //在该窗口所需的数据结构体,此时还没有分配内存要声明变量
{
    char Window_Switch ; //设置一个变量来判别当前的输入聚焦在哪个窗口，0代表在列表框
    WM_HWIN hIchild;  //存放子窗口的句柄
    int     Sel;  //索引号
};

struct SweepFreq SweepFreq_data = {0,0,0};
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "SweepFreq", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
    { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 0, 114, 240, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Listbox'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        LISTBOX_AddString(hItem, "SET_1");
        LISTBOX_AddString(hItem, "SET_2");
        LISTBOX_AddString(hItem, "SWfreq_Esc");
        LISTBOX_SetFont(hItem, GUI_FONT_20_1);  //设置字体

        //设置子窗口
        SweepFreq_data.hIchild = CreateSweep_First();
        WM_AttachWindowAt(SweepFreq_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
        WM_SetFocus(hItem); //设置聚焦为列表框

        // USER START (Optionally insert additional code for further widget initialization)
        // USER END

        break;

    //按键信息
    case WM_KEY:
        switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
        {
        case GUI_KEY_ESCAPE:
            if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)))//检测现在的聚焦是否在listbox上
            {
                GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
                CreateGen_Out();  //显示第二页面
            }
            else
            {

            }

            break;
        }
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_LISTBOX_0: // Notifications sent by 'Listbox'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                SweepFreq_data.Sel = LISTBOX_GetSel(pMsg->hWinSrc);
                if (SweepFreq_data.Sel == 0) //SET_1
                {
                    if (WM_IsWindow(SweepFreq_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(SweepFreq_data.hIchild, 1); //删除上一个窗口
                    }
                    SweepFreq_data.hIchild = CreateSweep_First(); //创建窗口，第一个界面
                    WM_AttachWindowAt(SweepFreq_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)); //聚焦到列表框
                }
                else if (SweepFreq_data.Sel == 1) //SET_2
                {
                    if (WM_IsWindow(SweepFreq_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(SweepFreq_data.hIchild, 1); //删除上一个窗口
                    }
                    SweepFreq_data.hIchild = CreateSweep_Two(); //第二个界面
                    WM_AttachWindowAt(SweepFreq_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));//聚焦到列表框
                }

                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSweepFreq
*/
WM_HWIN CreateSweepFreq(void);
WM_HWIN CreateSweepFreq(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
