/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x0D)
#define ID_PROGBAR_1 (GUI_ID_USER + 0x0E)
#define ID_SLIDER_0 (GUI_ID_USER + 0x0F)
#define ID_TEXT_0 (GUI_ID_USER + 0x10)
#define ID_TEXT_1 (GUI_ID_USER + 0x11)
#define ID_TEXT_2 (GUI_ID_USER + 0x12)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x13)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "COAX_face_3", ID_WINDOW_0, 0, 0, 285, 240, 0, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 15, 27, 250, 37, 0, 0x0, 0 },
    { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 15, 167, 250, 20, 0, 0x0, 0 },
    { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 15, 109, 250, 20, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 15, 5, 85, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 15, 83, 109, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 15, 142, 111, 20, 0, 0x64, 0 },
    { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 18, 203, 114, 20, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 151, 203, 111, 20, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
signed char COAX_Gain=-80;
static GUI_RECT Rect =
{
    95, /* 矩形区左上角 X 坐标位置 */
    3, /* 矩形区左上角 Y 坐标位置 */
    115, /* 矩形区右下角 X 坐标位置 */
    23, /* 矩形区右下角 Y 坐标位置 */
};  //无效化矩形区域结构体
//显示滑块值
static void _ShowSlidervalue(void)
{
    GUI_SetColor(GUI_RED); //设置颜色
    GUI_SetTextMode(GUI_TM_TRANS); //设置透明模式
    GUI_SetFont(&GUI_Font20_1); //设置字体
    GUI_GotoXY(95, 3);  //设置位置
    GUI_DispDecMin(COAX_Gain); //显示值
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
        SLIDER_SetRange(hItem, -80, 0); //设置滑块范围
        SLIDER_SetValue(hItem, COAX_Gain); //设置滑块的值
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, GUI_FONT_16B_1);
        TEXT_SetText(hItem, "COAX_Gain:");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetText(hItem, "COAX_L_Meter:");
        TEXT_SetFont(hItem, GUI_FONT_16B_1);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetText(hItem, "COAX_R_Meter:");
        TEXT_SetFont(hItem, GUI_FONT_16B_1);
        //
        // Initialization of 'Checkbox'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
        CHECKBOX_SetText(hItem, "COAX_Invert");
        CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
        //
        // Initialization of 'Checkbox'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
        CHECKBOX_SetText(hItem, "COAX_Mute");
        CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        break;
		
		
	case WM_PAINT:
		_ShowSlidervalue(); //显示滑块值
		break;
	
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
        case ID_SLIDER_0: // Notifications sent by 'Slider'
            switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
				COAX_Gain = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect);
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
            switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_CHECKBOX_1: // Notifications sent by 'Checkbox'
            switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCOAX_face_3
*/

WM_HWIN CreateCOAX_face_3(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
