/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define list_box 0
#define child_box_0 1
#define child_box_1 2
#define child_box_2 3
#define child_box_3 4



struct Input1_third //在该窗口所需的数据结构体,此时还没有分配内存要声明变量
{
    char Window_Switch ; //设置一个变量来判别当前的输入聚焦在哪个窗口，0代表在列表框
    WM_HWIN hIchild;  //存放子窗口的句柄
    int     Sel;  //索引号
};

struct Input1_third Input1_third_data={list_box,0,0}; //声明结构体变量

//初始化
//Iput1
//Input_data Input1_data1=
//{
//	0 , //Invert未选中
//	0 ,
//	0 ,
//	0 ,
//	-80,
//	-80,
//	-80,
//	-80,
//	-80,
//	-80,
//	-80,
//	-80,
//	-80,
//};

Input_data Input1_data1[8]=
{
	
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input1
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input2
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input3
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input4
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input5
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input6
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //input7
	{0 , 0 ,0 ,0 ,-80,-80,-80,-80,-80,-80,-80,-80,-80,}, //iuput8

};


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const char input_esc[][11] =
{
	"Input1_Esc",
	"Input2_Esc",
	"Input3_Esc",
	"Input4_Esc",
	"Input5_Esc",
	"Input6_Esc",
};
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 }, //不支持WM_CREATE
    { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 0, 114, 240, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       获得
*/

// USER START (Optionally insert additional static code)
//USER END

/*********************************************************************
*
*       _cbDialog  对话框回调函数
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
	WM_HWIN hItemold;
    WM_HWIN hchild_check;
    int     NCode;
    int     Id;

    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {

    case WM_INIT_DIALOG:
        Input1_third_data.Sel = 0; //列表框的选项
        //
        // Initialization of 'Listbox'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        hchild_check = hItem;
        LISTBOX_AddString(hItem, "SET_1");
        LISTBOX_AddString(hItem, "SET_2");
        LISTBOX_AddString(hItem, "SET_3");
        LISTBOX_AddString(hItem, "SET_4");
        LISTBOX_AddString(hItem, "SET_5");
        LISTBOX_AddString(hItem, input_esc[INPUT_channel]);//显示Esc
//        LISTBOX_EnableWrapMode(hItem, 1); //启用自动换行模式,会提示要删除的块已经在_Free()中
        LISTBOX_SetFont(hItem, GUI_FONT_20_1);  //设置字体
	
	
		
//
//
//        //设置子窗口
        Input1_third_data.hIchild = CreateWindow_Child();              //创建一个子窗口,并获得子窗口的句柄，右边子窗口
        WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
        WM_SetFocus(hItem); //设置聚焦为列表框
        break;

    case WM_KEY:
        switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
        {
		//ESC消息
        case GUI_KEY_ESCAPE:

            if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)))//检测现在的聚焦是否在listbox上
            {
                GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
                hWin_now = CreateINPUT_CHANNEL();  //显示第二页面
            }
            else
            {
                Input1_third_data.Window_Switch = list_box;
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)); //聚焦到列表框
                LISTBOX_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0),Input1_third_data.Sel); //返回列表框所选项目
            }

            break;
		
		//ENTER消息
        case GUI_KEY_ENTER:
			//选项为0和聚焦在listbox
            if(Input1_third_data.Sel != 5 && WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)) )
            {
                Input1_third_data.Window_Switch = child_box_0; //表示在第一个子窗口
				WM_SetFocus(WM_GetFirstChild(Input1_third_data.hIchild));//聚焦右边窗口的第一个子窗口
            }
//			else if(Input1_third_data.Sel == 1 && WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)))
//			{
//				Input1_third_data.Window_Switch = child_box_1; //表示在第二个子窗口
//				WM_SetFocus(WM_GetFirstChild(Input1_third_data.hIchild));//聚焦右边窗口的第一个子窗口
//			}
            else if(Input1_third_data.Sel == 5) //
            {
                Input1_third_data.Sel = 0;
                GUI_EndDialog(pMsg->hWin, 0);      //关闭当前窗口
                hWin_now = CreateINPUT_CHANNEL();  //显示第二页面
            }
            break;
        }
        break;
	case WM_PAINT:
//		hItemold = WM_SelectWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
//		GUI_DrawGradientRoundedH(35, 100, 180, 130, 5, 0x0000FF, 0x00FFFF);
//		GUI_SetColor(GUI_BLACK);
//		GUI_SetFont(GUI_FONT_32_1);
//		GUI_DispStringAt("Hello world", 0, 0);
//		WM_SelectWindow(hItemold);
		break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_LISTBOX_0: // Notifications sent by 'Listbox'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED: //不支持回车键信息，支持触摸点击
                // USER START (Optionally insert code for reacting on notification message)

                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                if(Input1_third_data.Sel == 5)
                {
                    Input1_third_data.Sel = 0;
                    GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
                    hWin_now = CreateINPUT_CHANNEL();  //显示第二页面
                }    
				// USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                Input1_third_data.Sel = LISTBOX_GetSel(pMsg->hWinSrc); //更改选项Sel
                if (Input1_third_data.Sel == 0) //SET_1
                {
                    if (WM_IsWindow(Input1_third_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(Input1_third_data.hIchild, 1); //删除上一个窗口
                    }
                    Input1_third_data.hIchild = CreateWindow_Child(); //创建窗口，第一个界面
                    WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)); //聚焦到列表框
                }
                else if (Input1_third_data.Sel == 1) //SET_2
                {
                    if (WM_IsWindow(Input1_third_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(Input1_third_data.hIchild, 1); //删除上一个窗口
                    }
                    Input1_third_data.hIchild = CreateSecond_Child(); //第二个界面
                    WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));//聚焦到列表框
                }
                else if (Input1_third_data.Sel == 2) //SET_3
                {
                    if (WM_IsWindow(Input1_third_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(Input1_third_data.hIchild, 1); //删除上一个窗口
                    }
                    Input1_third_data.hIchild = CreateThird_Child(); //第三个界面
                    WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));//聚焦到列表框

                }
                else if (Input1_third_data.Sel == 3) //SET_4
                {
                    if (WM_IsWindow(Input1_third_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(Input1_third_data.hIchild, 1); //删除上一个窗口
                    }
                    Input1_third_data.hIchild = CreateFour_Child(); //第四个界面
                    WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));//聚焦到列表框
                }
                else if (Input1_third_data.Sel == 4) //SET_5
                {
                    if (WM_IsWindow(Input1_third_data.hIchild)) //检测句柄是否有效
                    {
                        GUI_EndDialog(Input1_third_data.hIchild, 1); //删除上一个窗口
                    }
                    Input1_third_data.hIchild = CreateFive_Child(); //第五个界面
                    WM_AttachWindowAt(Input1_third_data.hIchild, pMsg->hWin, 115, 0); //把窗口加到该父窗口中
                    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));//聚焦到列表框
                }
//                else if (Input1_third_data.Sel == 5) //Esc项
//                {

//                }
//                if (WM_IsWindow(Input1_third_data.hIchild))
//                {
//                    WM_InvalidateWindow(Input1_third_data.hIchild);  //无效化子窗口，让界面重新刷新子窗口
//                }

                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
/*************************************用户自定义信息**************************************/
	//退出键
	case MSG_KEY_ESC:  
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1);  //ESC
		break;
	
	//CONTROL键
	case MSG_KEY_CONTROL:
		if(WM_HasFocus(Get_child_hWin(2))) //是否聚焦在复选框上
		{
			GUI_SendKeyMsg(GUI_KEY_SPACE, 1);   //切换 CHECKBOX 控件的选中状态。
			if(CHECKBOX_GetState(Get_child_hWin(2))==0)
			{
				Input1_data1[INPUT_channel].Invert = 0;  //复选框状态为未选中
			}
			else if(CHECKBOX_GetState(Get_child_hWin(2))==1)
			{
				Input1_data1[INPUT_channel].Invert = 1;  //复选框状态为选中
			}
		}
		else 
		{
			GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定消息
		}
		break;
	
	//CONTROL左转
	case MSG_KNOB_CONTROL_LEFT:
		//不同的聚焦要不同的信息
		if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))) //列表框
		{
			GUI_SendKeyMsg(GUI_KEY_DOWN, 1);    //向下
		}
		else 
		{
			GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		}
		break;
	
	//CONTROL右转
	case MSG_KNOB_CONTROL_RIGHT:
		if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0)))
		{
			GUI_SendKeyMsg(GUI_KEY_UP, 1);      //向上
		}
		else 
		{
			GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		}
		break;
		
	//OUT左转
	case MSG_KNOB_OUT_LEFT:
		if(Input1_third_data.Sel != 1)
		{
			GUI_SendKeyMsg(GUI_KEY_RIGHT,1); //滑块左移
		}
		else if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))) //检测是否在选项框
		{
			
		}
		else if(Input1_third_data.Sel == 1)
		{
			GUI_SendKeyMsg(GUI_KEY_UP,1);   //数值增加
		}
	break;
	
	//OUT右转
	case MSG_KNOB_OUT_RIGHT:
		if(Input1_third_data.Sel != 1)
		{
			GUI_SendKeyMsg(GUI_KEY_LEFT,1); //滑块右移
		}
		else if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))) //检测是否在选项框
		{
			
		}
		else if(Input1_third_data.Sel == 1)
		{
			GUI_SendKeyMsg(GUI_KEY_DOWN,1); //数值减少
		}
	break;
		
	//INPUT
	case MSG_KEY_INPUT:
		WM_SendMessageNoPara(hWin_now, MSG_KEY_CONTROL);
		break;
	
	//OUT
	case MSG_KEY_OUTPUT:
		OUTPUT_channel = 0;
        GUI_EndDialog(pMsg->hWin,0);     //结束当前页面
        hWin_now = CreateOut_face();     //输出OUT子界面
		break;
	
	//SYS
	case MSG_KEY_SYSTEM:
		GUI_EndDialog(pMsg->hWin,0);
		hWin_now = CreateSystem();
		break;
/**************************************END***********************************************/
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Createthird_layer(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
