/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x05)
#define ID_BUTTON_4 (GUI_ID_USER + 0x06)
#define ID_BUTTON_5 (GUI_ID_USER + 0x07)
#define ID_TEXT_1 (GUI_ID_USER + 0x08)
#define MSG_CreateInfo      (GUI_ID_USER + 0x0E)

#define Font_Text  GUI_FONT_24_1   //字体
extern GUI_CONST_STORAGE GUI_BITMAP bmlannge_yellow;  //橙色logo
extern GUI_CONST_STORAGE GUI_BITMAP bmlannge_white;   //白色logo
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static char Main_channel=0;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Mainface", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 17, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 150, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 280, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 17, 155, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 150, 155, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 280, 155, 103, 71, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 317, 16, 63, 20, 0, 0x64, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*
*********************************************************************************************************
*	函 数 名: _cbDialog
*	功能说明: 对话框回调函数
*	形    参: pMsg  回调参数
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem, hItem1;
	int     NCode;
	int     Id;


	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Text'
		//
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//		TEXT_SetText(hItem, "Lannge");
//		TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
//		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0xffffffff));

		//
		// 初始按钮控件 INPUT
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, "INPUT");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 COAX_IN
		//
		hItem1 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetText(hItem1, "COAX_IN");
		BUTTON_SetFont(hItem1, Font_Text);

		//
		// 初始按钮控件 Gen_Out
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, Font_Text);
		BUTTON_SetText(hItem, "Gen_Out");

		//
		// 初始按钮控件 OUTPUT
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetText(hItem, "OUTPUT");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 SYSTEM
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetText(hItem, "SYSTEM");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 MODE
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, Font_Text);
		BUTTON_SetText(hItem, "MODE");

		//
		// 初始Text控件
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//		TEXT_SetText(hItem, "00:00");
		TEXT_SetFont(hItem, GUI_FONT_24_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0xffffffff));
		
		switch(Main_channel)
		{
			case 0:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				break;
			
			case 1:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
				break;
			
			case 2:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				break;
			
			case 3:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				break;
			
			case 4:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				break;
			
			case 5:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
				break;
			
		}
		WM_SetFocus(hItem); //聚焦
		break;
		
//	case WM_KEY:
//		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
//		{
//
//		}
//		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_BUTTON_0://INPUT
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				/* 关闭当前对话框， 创建对话框2 */

				// USER END
				break;
			case WM_NOTIFICATION_RELEASED: 
				Main_channel = 0;
                GUI_EndDialog(pMsg->hWin, 0); //结束本界面
                hWin_now = Input_First(); //显示INPUT第一个界面
				break;
			}
			break;
		case ID_BUTTON_1: // COAX_IN
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Main_channel = 1;
                GUI_EndDialog(pMsg->hWin, 0); //结束本界面
				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
		case ID_BUTTON_2: //Gen_Out
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
                GUI_EndDialog(pMsg->hWin,0);   //结束本界面
				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
		case ID_BUTTON_3:  //OUTPUT
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				
				break;
			case WM_NOTIFICATION_RELEASED:
				Main_channel = 3;
                GUI_EndDialog(pMsg->hWin,0);     //结束当前页面
				hWin_now = Output_First(); //显示OUTPUT第一个界面
				break;

			}
			break;
		case ID_BUTTON_4: //SYSTEM
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:
				Main_channel = 4;
				GUI_EndDialog(pMsg->hWin,0);
				break;

			}
			break;
		case ID_BUTTON_5:  //MODE
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:
				Main_channel = 5;
				GUI_EndDialog(pMsg->hWin,0);
				break;

			}
			break;

		}
		break;

	case WM_PAINT:

		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();  //全屏黑色
		GUI_SetPenSize(3);
		GUI_SetColor(GUI_RED);
		GUI_DrawLine(0, 50, 400, 50); //画红线

		GUI_DrawBitmap(&bmlannge_yellow, 100, 0); //显示兰格logo
		break;
	
/***************************************************************************************/
	//以下为自定义信息
	
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//CONTROL按下
	case MSG_KEY_CONTROL:
		GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1);  //退出
		break;
	
	//INPUT
	case MSG_KEY_INPUT:
        GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = Input_First(); //显示INPUT第一个界面
		break;
//	
//	//OUT
//	case MSG_KEY_OUTPUT:
//        GUI_EndDialog(pMsg->hWin,0);     //结束当前页面
//		break;
//	
//	
//	//SYS
//	case MSG_KEY_SYSTEM:
//		GUI_EndDialog(pMsg->hWin,0);
//		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMainface
*/
WM_HWIN CreateMainface(void);
WM_HWIN CreateMainface(void) {
	WM_HWIN hWin;
	
	//设置皮肤
	
	Button_flex();   //按钮皮肤设置
	/////////////
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	return hWin;
}


/*************************** End of file ****************************/
