/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "BUTTON_Private.h"

#define First_y		34
#define Secend_y	68
#define Thirt_y		102
#define Four_y		136
#define Five_y		170
#define Six_y		204

#define First_x     0
#define Secend_x    104
#define Thirt_x     202
#define Four_x      304
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_0 (GUI_ID_USER + 0x04)
#define ID_BUTTON_1 (GUI_ID_USER + 0x05)
#define ID_BUTTON_2 (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_9 (GUI_ID_USER + 0x10)
#define ID_BUTTON_10 (GUI_ID_USER + 0x11)
#define ID_BUTTON_11 (GUI_ID_USER + 0x12)
#define ID_BUTTON_12 (GUI_ID_USER + 0x13)
#define ID_BUTTON_13 (GUI_ID_USER + 0x14)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static Output_Second_Data *Out_Second;


static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10, 0 },
	{ 20, 10 },
	{ 10, 20 },
};
// USER START (Optionally insert additional static data)
// USER END
//页面显示的字符串数据
static char face_string[][20] = 
{
	"NULL",
	"OUTPUT1 PAGE 1/3",
	"OUTPUT2 PAGE 1/3",
	"OUTPUT3 PAGE 1/3",
	"OUTPUT4 PAGE 1/3",
	"OUTPUT5 PAGE 1/3",
	"OUTPUT6 PAGE 1/3",
	"OUTPUT7 PAGE 1/3",
	"OUTPUT8 PAGE 1/3",

};


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	//第一标题
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	//LIMITER
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 59, 36, 294, 28, 0, 0, 0 },
	//INVERT
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 172, 194, 28, 0, 0, 0 },
	//DELAY
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 202, 172, 194, 28, 0, 0, 0 },

	/*创建按钮*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 68, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 102, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 136, 198, 32, 0, 0x0, 0 },

	/*创建复选框*/
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 5, 208, 90, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 107, 208, 90, 23, 0, 0x0, 0 },

	/*DELAY*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 202, 204, 98, 32, 0, 0x0, 0 },

	/*增减按钮*/
	//LIMITER
	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 208, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 208, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 208, 141, 20, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 370, 73, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 370, 107, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 370, 141, 20, 25, 0, 0x0, 0 },

	//DECAY
	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 104 + 202, 208, 20, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 175 + 200, 208, 20, 25, 0, 0x0, 0 },

	/*页面切换*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 5, 5, 20, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 375, 5, 20, 25, 0, 0x0, 0 },

	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

//右边三角形
#define BUTTON_H2P(h) (BUTTON_Obj*) GUI_ALLOC_h2p(h)

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	BUTTON_Obj * pObj; //用来提取出按钮的指针结构体，包含了各种信息

	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;
	pObj = BUTTON_H2P(hWin);

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}

		//绘制聚焦,如果不接受聚焦则此项不起作用
		if (pObj->Widget.State & WIDGET_STATE_FOCUS)
		{
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;


		//case WM_TOUCH:
		//	if (pMsg->Data.p) {  /* Something happened in our area (pressed or released) */
		//		if (pState->Pressed) {
		//			RMSTC_Value++;
		//			WIDGET_OrState(hWin, BUTTON_STATE_PRESSED);
		//			WM_NotifyParent(hWin, WM_NOTIFICATION_CLICKED);
		//		}
		//		else {
		//			/* React only if button was pressed before ... avoid problems with moving / hiding windows above (such as dropdown) */
		//			
		//		}
		//	}
		//	else {
		//		
		//	}
		//	break;
		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}
/******************************Show_Value 所需数据*****************************/
#include "stdio.h"
#define   	RMSTC_Y   	75
#define   	DECAY_Y		RMSTC_Y+34
#define		THRES_Y		DECAY_Y+34

#define 	DELAY_Y		THRES_Y+68


//定义无效区域
static const GUI_RECT InvaliRect_Value[][4] = {
	{ 250, 70, 	350, 	90 }, //RMSTC_Item
	{ 250, DECAY_Y-5,	350,	DECAY_Y+15}, //DECAY_Item
	{ 250, THRES_Y-5,	350,	THRES_Y+15}, //DECAY_Item
	{0},
	{0},
	{ 300, DELAY_Y-5,	400,	DELAY_Y+15}, //DECAY_Item
};
/*
*******************************************************************************************
* 函 数 名: Show_Value
* 功能说明: 显示数值
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/
static void Show_Value(void)
{
	char str[10];
	GUI_SetColor(GUI_BLACK);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(&GUI_Font20_1);
	
	//RMSTC
	snprintf(str,9,"%d",Out_Second->data.RMSTC_DATA);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,RMSTC_Y);          //以当前坐标为中心显示字符串

	//DECAY
	snprintf(str,9,"%d",Out_Second->data.DECAY_DATA);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,DECAY_Y);          //以当前坐标为中心显示字符串

	//THRES
	snprintf(str,9,"%d",Out_Second->data.THRSH_DATA);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,THRES_Y);          //以当前坐标为中心显示字符串

	//DELAY
	snprintf(str,9,"%d",Out_Second->data.DELAY_DATA);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,350,DELAY_Y);          //以当前坐标为中心显示字符串

}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem;
	int		NCode;
	int		Id;

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_INIT_DIALOG:
		//TEXT设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, Out_Second->String);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//LIMITER
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "OUTPUT_LIMITER");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//MUTE_AND_INVERT
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "MUTE_AND_INVERT");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_20B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//DELAY
		//COMPRESSOR
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "DELAY");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		/*按钮设置*/
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "RMSTC(dB/s)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "DECAY(dB/s)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_13B_1);  //设置字体
		BUTTON_SetText(hItem, "THRESHOLD(dB)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "DELAY(ms)");          //设置显示的字符串

		/*复选框*/
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "OUT_MUTE");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13_1);
		CHECKBOX_SetState(hItem,Out_Second->data.OUT_MUTE_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "OUT_INVERT");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13_1);
		CHECKBOX_SetState(hItem,Out_Second->data.OUT_INVERT_STA);

		/*重新设计按钮的外观*/
		//NOISEGATE
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//DELAY
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//页面切换
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		break;
	
		
	/**************************************子窗口发生变化通知消息***********************************************/	
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);  //获得是哪个子窗口发生变化
		NCode = pMsg->Data.v;          //子窗口发生什么变化
		switch(Id)
		{
			//RMSTC
			case ID_BUTTON_0:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0)); //改变聚焦
						Out_Second->Item = RMSTC_Item_Out;  //子选项改变
						break;

				}
				break;
			
			//DECAY
			case ID_BUTTON_1:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1)); //改变聚焦
						Out_Second->Item = DECAY_Item_Out;  //子选项改变
						break;

				}
				break;
			
			//THRESH
			case ID_BUTTON_2:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2)); //改变聚焦
						Out_Second->Item = THRES_Item_Out;  //子选项改变
						break;

				}
				break;
			
			//DELAY
			case ID_BUTTON_3:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3)); //改变聚焦
						Out_Second->Item = DELAY_Item_Out;  //子选项改变
						break;

				}
				break;
			
			//复选框
			//OUT_MUTE
			case ID_CHECKBOX_0:
					//发生什么变化
					switch (NCode)
					{
						//复选框已被点击
						case WM_NOTIFICATION_CLICKED:
							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0)); //改变聚焦
							Out_Second->Item = MUTE_Item_Out;
							break;

						//复选框已被释放
						case WM_NOTIFICATION_RELEASED:
							break;

						//复选框的状态已改变
						case WM_NOTIFICATION_VALUE_CHANGED:
							//因为用了CHECKBOX_SetState，所以无点击时也会进入该选项-次
							//为了让创建复选框时不进行状态标记的转换
							if(Out_Second->checkbox_sta & (0x01<<0))
							{
								if(Out_Second->data.OUT_MUTE_STA == 0)
								{
									Out_Second->data.OUT_MUTE_STA = 1;
								}
								else
								{
									Out_Second->data.OUT_MUTE_STA = 0;
								}
							}
							else
							{
								Out_Second->checkbox_sta |= (0x01<<0);
							}
							break;
					}
					break;
					
			//OUT_INVERT
			case ID_CHECKBOX_1:
					//发生什么变化
					switch (NCode)
					{
						//复选框已被点击
						case WM_NOTIFICATION_CLICKED:
							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1)); //改变聚焦
							Out_Second->Item = INVERT_Item_Out;
							break;

						//复选框已被释放
						case WM_NOTIFICATION_RELEASED:
							break;

						//复选框的状态已改变
						case WM_NOTIFICATION_VALUE_CHANGED:
							//因为用了CHECKBOX_SetState，所以无点击时也会进入该选项-次
							//为了让创建复选框时不进行状态标记的转换
							if(Out_Second->checkbox_sta & (0x01<<1))
							{
								if(Out_Second->data.OUT_INVERT_STA == 0)
								{
									Out_Second->data.OUT_INVERT_STA = 1;
								}
								else
								{
									Out_Second->data.OUT_INVERT_STA = 0;
								}
							}
							else
							{
								Out_Second->checkbox_sta |= (0x01<<1);
							}
							break;
					}
					break;		
				
			//往左切换界面
			case ID_BUTTON_12:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						
						break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Output_Four();      //切换下一个界面
						break;
				}
				break;
			
			//往右切换界面
			case ID_BUTTON_13:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						
						break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Output_Third();      //切换下一个界面
						break;
				}
				break;
		}
		break;
	
	case WM_PAINT:
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//标题项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		//LIMITER
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(0, First_y, 400, 64, 4);

		//白色条
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(202, 68, 396, 98, 4);
		GUI_FillRoundedRect(202, 102, 396, 132, 4);
		GUI_FillRoundedRect(202, 136, 396, 166, 4);

		//第四项
		GUI_SetColor(GUI_BLUE);
		//MUTE_AND_INVERT
		GUI_FillRoundedRect(0, 170, 198, 200, 4);
		//MUTE
		GUI_FillRoundedRect(0, 204, 98, 234, 4);
		//INVERT
		GUI_FillRoundedRect(102, 204, 198, 234, 4);

		//右边第二项
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(202, 170, 398, 200, 4);

		//白色条
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(304, 204, 396, 234, 4);
		
		
		//显示各个子选项数值
		Show_Value();
		break;
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		//子选项指示
		if(Out_Second->Item == DELAY_Item_Out)
		{
			Out_Second->Item = RMSTC_Item_Out;
		}
		else
		{
			Out_Second->Item++;
		}
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		if(Out_Second->Item == RMSTC_Item_Out)
		{
			Out_Second->Item = DELAY_Item_Out;
		}
		else
		{
			Out_Second->Item--;
		}
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
		
	//CONTROL按下
	case MSG_KEY_CONTROL:
		if((Out_Second->Item == MUTE_Item_Out)||(Out_Second->Item == INVERT_Item_Out)) //IN_MUTE_Item和IN_INVERT_Item项
		{
			GUI_SendKeyMsg(GUI_KEY_SPACE,1);
		}
		else
		{
			GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		}
		break;
		
	//ESC
	case MSG_KEY_ESC:
		GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
        hWin_now = Output_First();  //显示Input_First页面
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
		switch(Out_Second->Item)
		{
			case RMSTC_Item_Out:
				
				//RMSTC值减少
				Value_Change_dec(&Out_Second->data.RMSTC_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item]); //无效化该区域重新刷新
				break;
			
			case DECAY_Item_Out:
				//DECAY值减少
				Value_Change_dec(&Out_Second->data.DECAY_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[DECAY_Item_Out]); //无效化该区域重新刷新
				break;
			
			case THRES_Item_Out:
				//THRES值减少
				Value_Change_dec(&Out_Second->data.THRSH_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[THRES_Item_Out]); //无效化该区域重新刷新
				break;
			
			case DELAY_Item_Out:
				//DELAY值减少
				Value_Change_dec(&Out_Second->data.DELAY_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[DELAY_Item_Out]); //无效化该区域重新刷新
				break;
		}
		break;
		
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
		switch(Out_Second->Item)
		{
			case RMSTC_Item_Out:
				
				//RMSTC值增加
				Value_Change_add(&Out_Second->data.RMSTC_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[RMSTC_Item_Out]); //无效化该区域重新刷新
				break;
			
			case DECAY_Item_Out:
				//DECAY值增加
				Value_Change_add(&Out_Second->data.DECAY_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[DECAY_Item_Out]); //无效化该区域重新刷新
				break;
			
			case THRES_Item_Out:
				//THRES值增加
				Value_Change_add(&Out_Second->data.THRSH_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[THRES_Item_Out]); //无效化该区域重新刷新
				break;
			
			case DELAY_Item_Out:
				//DELAY值增加
				Value_Change_add(&Out_Second->data.DELAY_DATA,&Out_Second->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[DELAY_Item_Out]); //无效化该区域重新刷新
				break;
		}
		break;
		
	//没有旋钮动作
	case MSG_KNOB_NULL:
		Out_Second->Key_count = 0;
		break;
	
	
	//页面切换
	case MSG_KNOB_OUT_LEFT:	
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Output_Third();      //切换下一个界面
		break;
	
	case MSG_KNOB_OUT_RIGHT:
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Output_Four();      //切换下一个界面
		break;
	/*********************************END***************************************/

	//释放动态内存
	case WM_DELETE:
		myfree(0,Out_Second); //释放动态数据
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//初始化数据
static void Init_data(Output_Second_Data *L)
{
	L->face_switch		=		OUTPUT_CHANNEL;
	L->Item				=		RMSTC_Item_Out;
	L->String			=		face_string[OUTPUT_CHANNEL];
	L->Time_count		=		0;
	L->hItime			=		0;
	L->Key_count		=		0;
	L->checkbox_sta		=		0;
	
	//数据初始化
	L->data.RMSTC_DATA  =		0;
	L->data.DECAY_DATA	=		0;
	L->data.THRSH_DATA	=		0;
	L->data.OUT_INVERT_STA 	=	0;
	L->data.OUT_MUTE_STA	=	0;
	L->data.DELAY_DATA	=		0;

}


WM_HWIN Output_Second(void) {
	WM_HWIN hWin;
	
	//申请数据
	Out_Second = (Output_Second_Data *)mymalloc(0,sizeof(Output_Second_Data));
	
	if(Out_Second == NULL)
	{
		return 0;
	}
	else
	{
		Init_data(Out_Second);//初始化数据
	}
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
