/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)
#define ID_BUTTON_6 (GUI_ID_USER + 0x07)
#define ID_BUTTON_7 (GUI_ID_USER + 0x08)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
char OUTPUT_channel = 0 ; //输出通道标志
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Out_face", ID_FRAMEWIN_0, 0, 0, 400, 240, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Out_1", ID_BUTTON_0, 8, 33, 80, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Out_2", ID_BUTTON_1, 108, 33, 80, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Out_3", ID_BUTTON_2, 205, 33, 80, 60, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Out_4", ID_BUTTON_3, 302, 33, 80, 60, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Out_5", ID_BUTTON_4, 8, 120, 80, 60, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Out_6", ID_BUTTON_5, 108, 120, 80, 60, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Out_7", ID_BUTTON_6, 205, 120, 80, 60, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Out_8", ID_BUTTON_7, 302, 120, 80, 60, 0, 0x0, 0 },

    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
/*********************************************************************
*
*       框架窗口回调函数
*/

static void _cbFramewin(WM_MESSAGE * pMsg)
{
    WM_HWIN hWin;

    hWin = pMsg->hWin; //获得句柄

    switch (pMsg->MsgId)
    {
    case WM_NOTIFY_PARENT:
        if (pMsg->Data.v == WM_NOTIFICATION_RELEASED)
        {
            int Id = WM_GetId(pMsg->hWinSrc);      // Id of widget
            if (Id == GUI_ID_CLOSE)  //因为没对关闭按钮进行处理所以没反应
            {
                GUI_EndDialog(hWin, 0); //关闭当前窗口
                CreateMainface();  //显示主页面
            }
        }
        break;
    default:
        FRAMEWIN_Callback(pMsg); //处理默认信息
    }
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Out_face'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        FRAMEWIN_SetTitleHeight(hItem, 40);
        FRAMEWIN_SetText(hItem, "OUT_CHANNEL");
        FRAMEWIN_SetFont(hItem, GUI_FONT_32_1);
        FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
        FRAMEWIN_AddCloseButton(hItem, FRAMEWIN_BUTTON_RIGHT, 0); //添加一个关闭按钮
        WM_SetCallback(hItem,_cbFramewin); //设置回调函数
        //
        // Initialization of 'Out_1'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetText(hItem, "Out_1");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_2'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetText(hItem, "Out_2");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_3'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetText(hItem, "Out_3");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_5'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetText(hItem, "Out_4");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_6'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetText(hItem, "Out_5");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_4'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetText(hItem, "Out_6");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_7'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        BUTTON_SetText(hItem, "Out_7");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Out_8'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        BUTTON_SetText(hItem, "Out_8");
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
		
		switch(OUTPUT_channel)
		{
			case 0:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				break;
			
			case 1:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
				break;
			
			case 2:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				break;
			
			case 3:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				break;
			
			case 4:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				break;
			
			case 5:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
				break;
			
			case 6:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
				break;
			
			case 7:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
				break;
		}
		WM_SetFocus(hItem); //聚焦
        break;
    //按键信息处理
    case WM_KEY:
        switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
        {
        case GUI_KEY_ESCAPE:
            GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
            hWin_now = CreateMainface();  //显示主页面
            break;
        }
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'Out_1'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 0;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'Out_2'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                
			    OUTPUT_channel = 1;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
			    // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by 'Out_3'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 2;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_3: // Notifications sent by 'Out_5'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 3;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_4: // Notifications sent by 'Out_6'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 4;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_5: // Notifications sent by 'Out_4'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 5;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_6: // Notifications sent by 'Out_7'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 6;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_7: // Notifications sent by 'Out_8'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				OUTPUT_channel = 7;
                GUI_EndDialog(pMsg->hWin, 0);
                hWin_now = CreateOutput1_third_face(); //显示第三页面
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
		
/********************************自定义信息*****************************************/
	case MSG_KNOB_CONTROL_LEFT:
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	case MSG_KNOB_CONTROL_RIGHT:
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	case MSG_KEY_CONTROL:
		GUI_SendKeyMsg(GUI_KEY_ENTER, 1);  //确定
		break;
	
	case MSG_KEY_ESC:
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1); //ESC
		break;
	
	//INPUT
	case MSG_KEY_INPUT:
		INPUT_channel = 0;  //输入通道聚焦位置标志
        GUI_EndDialog(pMsg->hWin, 0); //结束本界面
        hWin_now = CreateINPUT_CHANNEL(); //显示INPUT子界面
		break;
	
//	//OUT
	case MSG_KEY_OUTPUT:
		GUI_SendKeyMsg(GUI_KEY_ENTER, 1);  //确定
		break;
	
	//SYS
	case MSG_KEY_SYSTEM:
		GUI_EndDialog(pMsg->hWin,0);
		hWin_now = CreateSystem();
		break;
/*******************************END*****************************************/
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateOut_face
*/

WM_HWIN CreateOut_face(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hWin =  WM_GetClientWindow(hWin);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
